services:

  nginx:
    image: nginx:1-alpine
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 20MB
  
  api1: &api
    build:
      context: ./PaymentGateway
      dockerfile: Dockerfile
    image: rinha-backend-2025
    container_name: rinha-api1
    hostname: api1
    environment:
      - AppPort=8080
      - RedisConfig=redis:6379
      - PaymentProcessors_Default_BaseAddress=http://payment-processor-default:8080
      - PaymentProcessors_Fallback_BaseAddress=http://payment-processor-fallback:8080
      - HealthCheckMode=Server
      - ProcessingBatchSize=10
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 100MB

  api2:
    <<: *api
    container_name: rinha-api2
    hostname: api2
    environment:
      - AppPort=8080
      - RedisConfig=redis:6379
      - PaymentProcessors_Default_BaseAddress=http://payment-processor-default:8080
      - PaymentProcessors_Fallback_BaseAddress=http://payment-processor-fallback:8080
      - HealthCheckMode=Client
      - ProcessingBatchSize=10

  redis:
    image: redis:8-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 80MB

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true