services:

  nginx:
    image: nginx:1-alpine
    container_name: rinha-nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 20MB
  
  api1: &api
    build:
      context: ./PaymentGateway
      dockerfile: Dockerfile
    image: rinha-backend-2025
    container_name: rinha-api1
    hostname: api1
    environment:
      - HealthCheckMode=Server
      - NumOfProcessingTaks=40
      - PercentageOfMostHealthy=10
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 60MB

  api2:
    <<: *api
    container_name: rinha-api2
    hostname: api2
    environment:
      - HealthCheckMode=Client
      - NumOfProcessingTaks=40
      - PercentageOfMostHealthy=10

  redis:
    image: redis:8-alpine
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 5000 --protected-mode no --hz 1
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 80MB

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true